### 유저 서비스 heath 조회
GET {{host}}/user-service/health

### 카탈로그 서비스 heath 조회
GET {{host}}/catalog-service/health

### 주문 서비스 heath 조회
GET {{host}}/order-service/health

### 유저 등록
POST {{host}}/user-service/users
Content-Type: application/json

{
    "name": "진크",
    "email": "jincrates@email.com",
    "password": "12345678"
}

### 유저 전체 조회
GET {{host}}/user-service/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJqaW5jcmF0ZXMiLCJpYXQiOjE2NzE1NDYzMjYsImV4cCI6MTY3MTYzMjcyNiwic3ViIjoiamluY3JhdGVzQGVtYWlsLmNvbSJ9.IWYXASmxaqkBvnHziFtYPu5Sl1HeOC_Rejf-P-4UZtYxn8QcQih5r3IogtQn_4agga7rAkYFMkYq0Wyx5fa0uw

### 유저 상세 조회
GET {{host}}/user-service/users/b7c9d8ca-14e2-4cdf-88ae-2f94a5e0d0c5

### 카탈로그 전체 조회
GET {{host}}/catalog-service/catalogs

### 주문 등록
POST {{host}}/order-service/b7c9d8ca-14e2-4cdf-88ae-2f94a5e0d0c5/orders
Content-Type: application/json

{
  "productId": "CATALOG-0001",
  "qty": 10,
  "unitPrice": 1500
}

### 주문 조회
GET {{host}}/order-service/b7c9d8ca-14e2-4cdf-88ae-2f94a5e0d0c5/orders

### 유저 로그인
POST {{host}}/user-service/login
Content-Type: application/json

{
  "email": "jincrates@email.com",
  "password": "12345678"
}

### 게이트웨이
GET {{host}}/actuator/health

### 유저 서비스
GET {{host}}/user-service/actuator/health
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJqaW5jcmF0ZXMiLCJpYXQiOjE2NzE4NjIwNjksImV4cCI6MTY3MTk0ODQ2OSwic3ViIjoiamluY3JhdGVzQGVtYWlsLmNvbSJ9.SNSKRHkUobTS2bl3wWiqKRaaK724V9MldjsRWLTqCVpWI6EJAaUhsbqBhGOZOibj69Y6NrRC0W4r-pXXMODE5w

### 전체 config 파일 refresh
POST {{host}}/user-service/actuator/busrefresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJqaW5jcmF0ZXMiLCJpYXQiOjE2NzIwNjQyMjQsImV4cCI6MTY3MjE1MDYyNCwic3ViIjoiamluY3JhdGVzQGVtYWlsLmNvbSJ9.L4TfCre82Rsg-Oxo4kaJl4Cv1RcKg73X22y0_Qv01G5oZrrhLnkmAgJ6_aoVZevFdhm05TbmaEh5MLa7SbnzyA

### 암호화
POST {{config-server}}/encrypt
Content-Type: 'text/plain'

jincrates

### 복호화
POST {{config-server}}/decrypt
Content-Type: 'text/plain'

AQBCwNF1dQzLQry0Wy8cu7DQ8gVbZQLSVeYdblPSmtfssuVJHSSQmy8SnpMxjypnNPuSNbIH6AUOs37+5H8dfEJnQIjvshGjdGT5J6neLiLgJPAH/wf6yTW8ys935z0Ukp+W7ngcgZ9DulB+5C7Xu5IdHRiayy82SIHxv0WPoO1X56RpfVT466JXHVzfYWvUp9DwIx1KNwTxcHs5ThYVJncuWi03spX5teeLcQAvvNu8sxP67sLStSZWx5u9tiHrlCS+ANSdl7Lp/OhFO+jPLJ+Vz8ZsJnsBIHp2lqCkNEUlUUtV8VtGYDffIK8I7FCPqxw0GoMs/EjYQ3+crhDxtTjMRL0xbsQykqIYJwp5nlK8oTNKUUIeUsLBMqK1lCr48Ug=


### 유저 설정정보 확인
GET {{config-server}}/user-service/default