server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jincrates/springcloud-ecommerce
#          username: [your username]
#          password: [your password]
          default-label: develop
          searchPaths:
            - 'env'
#            - 'env/*'
