# https://inf.run/TMrn
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/projects/jin-space/env/native-file-repo
        git:
          uri: https://github.com/jincrates/springcloud-ecommerce
#          username: [your username]
#          password: [your password]
          default-label: develop
          searchPaths:
            - 'env'
#            - 'env/*'
