server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jincrates/springcloud-ecommerce/blob/master/config-service/src/main/resources
#          username: [your username]
#          password: [your password]
