# https://inf.run/TMrn
server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/projects/jin-space/env/native-file-repo
        git:
          uri: https://github.com/jincrates/springcloud-ecommerce
#          username: [your username]
#          password: [your password]
          default-label: develop
          searchPaths:
            - 'env'
#            - 'env/*'

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
